services:
  streamlit:
    hostname: streamlit
    container_name: streamlit
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../:/app
    env_file:
      - ../.env
    environment:
      - STREAMLIT_SERVER_PORT=8501

