# docker compose -f docker/docker-compose.yml -f docker/docker-compose-pgvector.yml up
# docker compose -f docker/docker-compose.yml -f docker/docker-compose-pgvector.yml down

services:
  streamlit:
    environment:
      - DATABASE_URL=postgresql://pgvector:pgvector@pgvector:5432/streamlit
    depends_on:
      - pgvector

  pgvector:
    image: pgvector/pgvector:pg17
    hostname: pgvector
    container_name: pgvector
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pgvector
      POSTGRES_PASSWORD: pgvector
      POSTGRES_DB: streamlit
      TZ: Asia/Seoul
      LANG: en_US.utf8
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./pgvector/init:/docker-entrypoint-initdb.d

volumes:
  pgvector_data:
